[package]
name = "archery"
description = "Abstract over the atomicity of reference-counting pointers"
version = "0.3.1-pre"
authors = ["Diogo Sousa <diogogsousa@gmail.com>"]

edition = "2018"

homepage = "https://github.com/orium/archery"
repository = "https://github.com/orium/archery"
documentation = "https://docs.rs/archery"
readme = "README.md"

keywords = [
    "rc",
    "arc",
    "reference-counting",
]

categories = [
    "concurrency",
    "memory-management",
    "rust-patterns",
]

license = "MPL-2.0"

# What to include when packaging.
include = [
    "/src/**/*.rs",
    "/Cargo.toml",
    "/LICENSE.md",
    "/README.md",
    "/release-notes.md",
]

[badges]
travis-ci = { repository = "orium/archery", branch = "master" }
codecov = { repository = "orium/archery", branch = "master", service = "github" }

[dependencies]
static_assertions = "1"

[dev-dependencies]
criterion = "0.3"
pretty_assertions = "0.6"
compiletest_rs = { version = "0.5", features = [ "tmp" ] }

[features]
default = ["std", "has_atomics"]
fatal-warnings = []
std = []
has_atomics = []

[[bench]]
name = "std_rc"
path = "benches/std_rc.rs"
harness = false

[[bench]]
name = "std_arc"
path = "benches/std_arc.rs"
harness = false

[[bench]]
name = "archery_shared_pointer_rc"
path = "benches/archery_shared_pointer_rc.rs"
harness = false

[[bench]]
name = "archery_shared_pointer_arc"
path = "benches/archery_shared_pointer_arc.rs"
harness = false
